version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-cont
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: banking-system
      MYSQL_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

volumes:
  db_data: